platform:ios,'7.0'
pod "YYKit",'~>1.0.7'
pod "MJRefresh",'3.1.12'
pod "FMDB",'~>2.6.2'
pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'ShareSDK3/ShareSDKUI'
pod 'MBProgressHUD', '~> 1.0.0'
